import React from 'react';
import { Copy } from 'lucide-react';
import { AIColorPalette } from '../services/geminiService';
import { getContrastColor } from '../utils/colorUtils';

interface PaletteDisplayProps {
  palette: AIColorPalette | null;
  loading: boolean;
  onCopy: (text: string) => void;
}

const PaletteDisplay: React.FC<PaletteDisplayProps> = ({ palette, loading, onCopy }) => {
  if (loading) {
    return (
      <div className="mt-8 p-6 bg-white rounded-2xl shadow-sm border border-slate-200 animate-pulse">
        <div className="h-6 bg-slate-200 rounded w-1/3 mb-4"></div>
        <div className="h-4 bg-slate-200 rounded w-2/3 mb-6"></div>
        <div className="flex h-24 rounded-xl overflow-hidden">
          {[1, 2, 3, 4, 5].map((i) => (
            <div key={i} className="flex-1 bg-slate-100 border-r border-white/50 last:border-0"></div>
          ))}
        </div>
      </div>
    );
  }

  if (!palette) return null;

  return (
    <div className="mt-8 p-6 bg-white rounded-2xl shadow-sm border border-slate-200">
      <div className="flex justify-between items-start mb-4">
        <div>
          <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
            ✨ {palette.name}
          </h3>
          <p className="text-sm text-slate-500 mt-1">{palette.description}</p>
        </div>
      </div>

      <div className="flex h-24 rounded-xl overflow-hidden shadow-inner ring-1 ring-black/5">
        {palette.colors.map((color, index) => (
          <div
            key={index}
            className="flex-1 flex items-end justify-center pb-2 group relative cursor-pointer transition-all hover:flex-[1.5]"
            style={{ backgroundColor: color }}
            onClick={() => onCopy(color)}
            title="Click to copy"
          >
            <span 
              className="text-xs font-mono font-bold opacity-0 group-hover:opacity-100 transition-opacity"
              style={{ color: getContrastColor(color) }}
            >
              {color}
            </span>
            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-colors" />
          </div>
        ))}
      </div>
      <div className="mt-2 text-xs text-right text-slate-400 italic">
        Generated by Gemini 2.5 Flash
      </div>
    </div>
  );
};

export default PaletteDisplay;